FROM node:17-alpine
WORKDIR /usr/aicrag
RUN npm install -g pnpm
RUN pnpm add -g pnpm
COPY ./package.json .
COPY ./pnpm-lock.yaml .
COPY ./.npmrc .
RUN pnpm install --unsafe-perm
COPY ./ ./
CMD ["pnpm", "run", "dev"]

