version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /usr/aicrag/node_modules
      - ./src/:/usr/aicrag/src/
      - ./tests/:/usr/aicrag/tests/
