############
# Build
FROM node:17-alpine as builder
WORKDIR /usr/aicrag
RUN npm install -g pnpm
COPY ./package.json .
COPY ./pnpm-lock.yaml .
RUN pnpm install --production
COPY ./ ./
RUN pnpm build

############
# Production
FROM nginx
RUN rm -rf /etc/nginx/conf.d
COPY ./config/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /usr/aicrag/build /usr/share/nginx/html

