version: '3.8'
services:
  aicrag_dev:
    container_name: aicrag_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /usr/aicrag/node_modules
      - ./src/:/usr/aicrag/src/
