name: Development
on:
  pull_request:
    branches:
      - development
  push:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
          cache: 'pnpm'

      - name: Install PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.27.2

      - name: Use cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test:ci

      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v4

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
